# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "jobs", :force => true do |t|
    t.column "created_at", :datetime
    t.column "created_by", :integer, :default => 0, :null => false
    t.column "title", :string, :default => "", :null => false
  end

  create_table "students", :force => true do |t|
    t.column "created_at", :datetime, :null => false
    t.column "created_by", :integer, :default => 0, :null => false
    t.column "title", :string, :default => "", :null => false
    t.column "tagline", :string, :default => "", :null => false
    t.column "description", :string, :default => "", :null => false
    t.column "looking_for", :string, :default => "", :null => false
    t.column "has_car", :integer, :default => 0, :null => false
    t.column "has_references", :integer, :default => 0, :null => false
  end

  create_table "taggings", :force => true do |t|
    t.column "tag_id", :integer
    t.column "taggable_id", :integer
    t.column "taggable_type", :string
  end

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  create_table "users", :force => true do |t|
    t.column "login", :string, :limit => 80, :default => "", :null => false
    t.column "salted_password", :string, :limit => 40, :default => "", :null => false
    t.column "email", :string, :limit => 60, :default => "", :null => false
    t.column "firstname", :string, :limit => 40
    t.column "lastname", :string, :limit => 40
    t.column "salt", :string, :limit => 40, :default => "", :null => false
    t.column "verified", :integer, :default => 0
    t.column "role", :string, :limit => 40
    t.column "security_token", :string, :limit => 40
    t.column "token_expiry", :datetime
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "logged_in_at", :datetime
    t.column "deleted", :integer, :default => 0
    t.column "delete_after", :datetime
  end

  create_table "welcomes", :force => true do |t|
  end

end
